apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        metrics_path: /metrics
        static_configs:
           - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
      - job_name: 'node'
        scrape_interval: 5s
        metrics_path: /metrics
        static_configs:
           - targets: ['172.18.90.40:9100']
           - targets: ['172.18.90.41:9100']
           - targets: ['172.18.90.42:9100']
           - targets: ['172.18.90.43:9100']
           - targets: ['172.18.90.44:9100']
           - targets: ['172.18.90.45:9100']
           - targets: ['172.18.90.46:9100']
           - targets: ['172.18.90.47:9100']
           - targets: ['172.18.90.48:9100']

