---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 9090
    nodePort: 30000
    name: prometheus
  selector:
    name: prometheus
  type: NodePort
---
